"""rename address

Revision ID: c48224680163
Revises: 3d967faac30a
Create Date: 2024-11-18 21:41:55.610463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48224680163'
down_revision = '3d967faac30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'location',  new_column_name='address')
    # ### end Alembic commands ###
